name: karelias monitoring

on:
  workflow_dispatch:

jobs:
  cve-alerts:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.10"

    - name: Install dependencies
      run: pip install -r requirements.txt firebase-admin

    - name: Create Firebase key file
      run: |
        echo "${{ secrets.FIREBASE_ADMIN_KEY }}" | base64 --decode > firebase_key.json
        
    - name: Run karelias feed script
      env:
        DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
        FIREBASE_KEY_FILE: firebase_key.json
      run: python karelias.py
